{% set name = "ploomber" %}
{% set version = "0.12.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a5fcf48cfbb262bda5d371819a1d4f1e12c64d1f6c7675745bba4463c59585c

build:
  number: 0
  noarch: python
  entry_points:
    - ploomber=ploomber.cli.cli:cmd_router
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - autopep8
    - click
    - humanize
    - importlib_resources
    - ipdb
    - ipykernel >=1.5.2
    - ipython
    - jinja2
    - jupyter_client >=5.3.1
    - jupytext
    - mistune
    - nbconvert >=5.6.0
    - networkx
    - notebook
    - nbformat
    - numpydoc
    - pandas
    - papermill
    - parso
    - ploomber-scaffold
    - pyarrow
    - pydantic
    - pyflakes
    - pygments
    - python >=3.6
    - pyyaml
    - sqlalchemy
    - sqlparse
    - tabulate
    - tqdm

test:
  imports:
    - ploomber
    - ploomber.cli
  commands:
    - pip check
    - ploomber --help
  requires:
    - pip

about:
  home: https://github.com/ploomber/ploomber
  summary: A convention over configuration workflow orchestrator. Develop locally (Jupyter or your favorite editor), deploy to Airflow or Kubernetes.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://ploomber.readthedocs.io/
  dev_url: https://github.com/ploomber/ploomber

extra:
  recipe-maintainers:
    - edublancas
    - rdmolony
