{% set name = "ploomber" %}
{% set version = "0.19.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 777e2fe0ef5e891c9e396d36c4795ab00cde393f0fa16b3f2925793016d810c0

build:
  number: 0
  noarch: python
  entry_points:
    - ploomber=ploomber_cli.cli:cmd_router
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - autopep8
    - click
    - humanize
    - importlib_resources
    - ipdb
    - ipykernel >=1.5.2
    - ipython <8
    - jinja2 <3.1
    - jupyter_client >=5.3.1
    - jupytext
    - mistune
    - nbconvert >=5.6.0
    - networkx
    - notebook
    - nbformat
    - papermill
    - parso
    - ploomber-scaffold
    - pydantic
    - pyflakes
    - pygments
    - python >=3.6
    - pyyaml
    - sqlalchemy
    - sqlparse
    - tabulate
    - tqdm
    - posthog
    - distro

test:
  imports:
    - ploomber
    - ploomber_cli
  commands:
    - pip check
    - ploomber --help
  requires:
    - pip

about:
  home: https://github.com/ploomber/ploomber
  summary: Write maintainable, production-ready pipelines using Jupyter or your favorite text editor. Develop locally, deploy to the cloud.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://ploomber.readthedocs.io/
  dev_url: https://github.com/ploomber/ploomber

extra:
  recipe-maintainers:
    - edublancas
    - rdmolony
